modLoader   = "javafml"
loaderVersion = "[1,)"
license     = "MIT"

[[mods]]
modId       = "hunted"
version     = "1.0.0"
displayName = "Hunted"
description = "Server hunt event mod."

[[dependencies.hunted]]
    modId        = "neoforge"
    type         = "required"
    versionRange = "[21.1,)"
    ordering     = "NONE"
    side         = "BOTH"

[[dependencies.hunted]]
    modId        = "minecraft"
    type         = "required"
    versionRange = "[1.21.1,)"
    ordering     = "NONE"
    side         = "BOTH"
